create table polls (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    apenom             VARCHAR(100) NOT NULL,
                    doc_type           VARCHAR(6) NOT NULL DEFAULT 'dni',
                    doc_number         INT NOT NULL,
                    birthdate          VARCHAR(10),
                    marital_state      VARCHAR(10),
                    street             VARCHAR(100),
                    city               VARCHAR(100),
                    province           VARCHAR(50),
                    phone              VARCHAR(25),
                    email              VARCHAR(50),
                    student_street     VARCHAR(100),
                    student_city      VARCHAR(100),
                    student_province   VARCHAR(50),
                    degree_to_follow   VARCHAR(10),
                    reasons_to_follow_degree TEXT,
                    knowdledge         VARCHAR(250),
                    school_title       VARCHAR(100),
                    school_area        VARCHAR(100),
                    school_name        VARCHAR(100),
                    school_type        VARCHAR(15),
                    school_year_grad   VARCHAR(4),
                    school_opinion     VARCHAR(15),
                    school_observation TEXT,
                    amount_hours_study VARCHAR(10),
                    study_resources    VARCHAR(20),
                    study_place        VARCHAR(10),
                    where_is_study_place TEXT,
                    extra_classes      VARCHAR(10),
                    extra_classes_subj VARCHAR(25),
                    study_techniques   TEXT,
                    hobbies            VARCHAR(50),
                    hobbies_extra_info TEXT,
                    job                VARCHAR(20),
                    user_id            INT NOT NULL
                    );



CREATE TABLE IF NOT EXISTS `users` (
       `id` int(11) unsigned NOT NULL auto_increment,
       `username` varchar(20) NOT NULL,
       `password` varchar(40) NOT NULL,
       `clear_password` varchar(20) default NULL,
       `first_name` varchar(20) default NULL,
       `last_name` varchar(20) default NULL,
       `email` tinytext NOT NULL,
       `status` enum('Active','Inactive') NOT NULL default 'Active',
       `last_login` datetime default NULL,
       `last_access` datetime default NULL,
       `created` datetime default NULL,
       `modified` datetime default NULL,
       PRIMARY KEY  (`id`),
       KEY `status` (`status`),
       KEY `login` (`username`,`password`)
     ) ENGINE=MyISAM;
